[package]
name = "pwa"
kind = "lib"
unsafe = false

[dependencies]
"array" = ""
"arith" = ""
"builder" = ""
"env" = ""
"file" = ""
"list" = ""
"path" = ""
"process" = ""
"result" = ""
"promise" = ""
"str" = ""
"wasm.bats-packages.dev/bridge" = ""
